server:
    port: 7070
javax:
    sql:
        DataSource:
            nwtis:
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:tcp://20.24.5.4:9092/nwtis_4;MODE=LEGACY
                    user: SA
                    password: ""
            h2:
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:tcp://localhost:9092/nwtis_4;MODE=LEGACY 
                    user: SA
                    password: ""
            hsqldb:
                dataSourceClassName: org.hsqldb.jdbc.JDBCDataSource
                dataSource:
                    url: jdbc:hsqldb:hsql://localhost:9001/nwtis_4
                    user: nwtis_4
                    password: nwtis#4
app:
    radari:
         adresa: 20.24.5.2
         mreznaVrata: 8000 
    vozila:
         adresa: 20.24.5.2
         mreznaVrata: 8001                   
    kazne:
         adresa: 20.24.5.2
         mreznaVrata: 8020
webservis:
    klijenti:
         nadzor:
              baseuri: http://20.24.5.1:8080/asaric_vjezba_08_dz_3_klijenti/mvc/
