SELECT * FROM KAZNE k ;

DELETE FROM VOZNJE ;
DELETE FROM PRACENEVOZNJE p ;
DELETE FROM KAZNE p ;

SELECT * FROM KAZNE k ;
SELECT * FROM VOZNJE v ;

SELECT * FROM VOZILA v ;

SELECT * FROM PRACENEVOZNJE p ;